# .github/workflows/scrape-jb-events.yml
name: Scrape Johnny Brenda’s Events

on:
  push:
    paths:
      - 'scripts/upsert_jb_events.py'
      - '.env.scraper'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            cloudscraper \
            beautifulsoup4 \
            python-dotenv \
            python-dateutil \
            certifi \
            supabase

      - name: Run Johnny Brenda’s scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python scripts/upsert_jb_events.py
