name: "BartramsGarden Scraper"

on:
  schedule:
    # Daily at 04:00 UTC (midnight Eastern)
    - cron: '0 4 * * *'
  workflow_dispatch: {}

jobs:
  scrape-bartramsgarden:
    name: Run Bartram's Garden scraper
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bartram's Garden scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python3 scripts/scrape-bartramsgarden.py
