name: Scrape Dolphin Tavern

on:
  schedule:
    - cron: '0 2 * * *'        # Runs at 02:00 UTC daily
  workflow_dispatch:         # Allows manual runs from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # assumes you have a requirements.txt; otherwise swap to a pip install line
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 python-dotenv supabase
          fi

      - name: Run Dolphin scraper
        run: |
          python3 scripts/scrape-dolphin.py
