name: Scrape Black Squirrel Club

on:
  schedule:
    # daily at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    concurrency:
      group: scrape-black-squirrel
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black Squirrel scraper
        run: python scripts/scrape-black-squirrel.py
        env:
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:              ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
