# .github/workflows/send-digest.yml
name: Send Digest (daily at 7 AM ET)

on:
  workflow_dispatch:            # still allows manual runs
  schedule:
    - cron: '0 11 * * *'        # every day at 11:00 UTC → 7:00 AM EDT

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase send-digest
        run: |
          curl -s -X POST \
            https://qdartpzrxmftmaftfdbd.supabase.co/functions/v1/send-digest \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
