name: Tufas Scraper (Daily)

on:
  schedule:
    # Runs every day at 11:30 UTC. Change as needed.
    - cron: "30 11 * * *"
  workflow_dispatch:

concurrency:
  group: tufas-scraper
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      # Supabase creds pulled from repo/environment secrets
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 python-dotenv "supabase>=2.4.0" lxml python-dateutil
          fi

      - name: Run scraper
        run: |
          # Update the path below if your script lives elsewhere
          python scripts/scrape_tufas.py
