# .github/workflows/upsert_fi_events.yml
name: Upsert FI Events

on:
  push:
    # only run when the FI scraper or your GitHub‑Actions config changes
    paths:
      - 'scripts/upsert_fi_events.py'
      - '.github/workflows/upsert_fi_events.yml'

jobs:
  upsert-fi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FI scraper & upsert
        env:
          SUPABASE_URL:            ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scripts/upsert_fi_events.py
